name: DevSecOps Fraud Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clonar Repositorio
      uses: actions/checkout@v4

    - name: 🛠️ Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: 🚀 Instalar y Configurar UV (Rust-powered package manager)
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: 📦 Instalar Dependencias del Sistema
      run: |
        uv venv
        uv pip install -r requirements.txt
        uv pip install bandit

    - name: 🛡️ Análisis Estático de Seguridad (SAST con Bandit)
      run: |
        # Usamos uv run para ejecutar bandit dentro del entorno virtual y excluimos carpetas locales
        uv run bandit -r . -x ./.venv,./venv,./mlruns -ll

    - name: 🧪 Ejecutar Suite de Pruebas Unitarias (Testing Automatizado)
      run: |
        # Usamos uv run para ejecutar las pruebas unitarias garantizando que cargue las librerías del venv
        uv run python test_pipeline.py